# Generated by Django 4.1 on 2022-08-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0002_work_place_phone_book_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone_book',
            name='work_info',
        ),
        migrations.AddField(
            model_name='phone_book',
            name='work_info',
            field=models.ManyToManyField(blank=True, null=True, to='phone_book.work_place'),
        ),
    ]
