# Generated by Django 4.1 on 2022-08-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0003_remove_phone_book_work_info_phone_book_work_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_book',
            name='work_info',
            field=models.ManyToManyField(to='phone_book.work_place'),
        ),
    ]
