# Generated by Django 4.1 on 2022-08-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0004_alter_phone_book_work_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='phone_book',
            name='family_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone_book.family_members'),
        ),
    ]
