# Generated by Django 4.1 on 2022-08-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0006_family_members_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_members',
            name='members',
        ),
        migrations.AlterField(
            model_name='phone_book',
            name='family_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone_book.family_members'),
        ),
    ]
