# Generated by Django 4.1 on 2022-08-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0007_remove_family_members_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='phone_book',
            name='family_members',
        ),
        migrations.DeleteModel(
            name='Family_Members',
        ),
        migrations.AddField(
            model_name='phone_book',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone_book.email'),
        ),
    ]
